- .travis-opam.sh
This PR is intended as a starting point for discussion on solving #1. I just did the easiest thing imaginable, not sure if I forgot something. If so, let me know.
> Added option for rebuilding reverse dependencies

- .travis-opam.sh
> OCAML_VERSION needs to be defined

- .travis-mirage.sh
pass in IP configuration as env vars
> mirage: pass static ip config to `make`

- .travis-mirage.sh
- .travis-ocaml.sh
- .travis-opam.sh
> shellcheck

- .travis-mirage.sh
- .travis-ocaml.sh
- .travis-opam.sh
Reverts ocaml/ocaml-travisci-skeleton#35
> Revert "shellcheck"

- .gitignore
- .merlin
- .travis-ocaml.sh
- .travis-opam.sh
- README.md
- travis_opam.ml
- yorick.ml
- yorick.mli
Oh reform it altogether. And let those that play your clowns
speak no more than is set down for them, for there be of them that
will themselves laugh, to set on some quantity of barren spectators
to laugh too, though in the meantime some necessary question of
the play be then to be considered. That's villainous, and shows
a most pitiful ambition in the fool that uses it. Go make you ready.
> Yorick, a fellow of infinite jest

- README.md
@samoht here, documentation :)
> document UPDATE_GCC_BINUTILS

- .gitignore
- .merlin
- .travis-mirage.sh
- travis_mirage.ml
Don't merge yet, still testing. Does for `.travis-mirage.sh` what @dsheets did for `.travis-opam.sh`.
@dsheets Some thoughts on `Yorick`:
+ Didn't realise that `$CWD` isn't maintained between `?|` commands
+ Should understand / be more consistent about output during execution (`set +ex` etc)
+ Need to use nested `"` to make sure shell and OCaml treat contents correctly (strings in which variable substitution is carried out) is a bit awkward
Other than that, mostly OK I think.
> Yorick mirage

- travis_mirage.ml
This reverts commit 7950dd2a11aa69e55b3393bd279a5ae7ca1da8de.
> Revert "Only deploy if the current branch is master"

- travis_mirage.ml
Fix https://github.com/mirage/mirage-www/issues/347
> Deploy only the master branch for the mirage scripts

- travis_opam.ml
Do not run the tests while testing DEPOPTS.
> Rework the installation of depopts

- .travis.yml
- opam
So much recursion, my head hurts.
> Enable travis testing

- .travis-docker.sh
More details and writeup on this shortly once its been better tested.
> Add a Docker-based Travis tester that invokes `travis-opam`

- .gitignore
- CHANGES
- travis_opam.ml
Also, add a CHANGES file. We should release after this is merged.
> Lint before pinning to avoid editor spinning

- opam
See ocaml/opam-repository#6332. Please delete this branch after merging/closing.
> opam: add ocamlbuild build dependency

- travis_mirage.ml
Reverts ocaml/ocaml-ci-scripts#91
> Revert "mirage: check in any generated .xl.in file"

- .travis-ocaml.sh
Signed-off-by: David Scott <dave@recoil.org>
> homebrew has updated to OCaml 4.03

- travis_mirage.ml
race is between build of `openmirage.org` and `mirage.io`
> reduce chances of conflict due to race

- travis_mirage.ml
> Pull after commit

- travis_mirage.ml
> More fixes after #111

- travis_mirage.ml
> Do not remove pre-existing build images

- .travis-docgen.sh
Some useful patches that fix race condition when travis job ends. :blush:
> docgen: Resync with upstream fixes

- .travis-ocaml.sh
This is in relation with the switch to trusty at ocaml/opam-repository#6902
> Force recompilation of old OCaml compilers.

- CHANGES
> release 1.03

- appveyor.yml
See https://github.com/fdopen/opam-repository-mingw/issues/30#issuecomment-265488298
> Use default diffutils on appveyor

- .merlin
- ci_opam.ml
Reverts ocaml/ocaml-ci-scripts#145
> Revert "Run depopts tests"

- ci_opam.ml
Fix a regression introduced in #152
> Fix running tests when using PACKAGE=name.version

- .travis-ocaml.sh
- .travis.yml
> Add support for OCaml 4.05+beta3.

- ci_opam.ml
- add `opam depext foo` to the "Prepare" step
- and add a "Simple.depopt" step
> travis: reorganise a bit the steps

- .travis-opam.sh
- appveyor-opam.sh
- ci_opam.ml
This is #180 without the jbuilder bits
> Better package name

- .travis-mirage.sh
> Fix travis-mirage script

- .travis-ocaml.sh
> Set variables before installing ppas

- .travis-ocaml.sh
This could happen if OPAM_INIT=false
> Call opam --version only if ocaml is present

- src/ci_opam.ml
Thanks to @AltGr for the magic runes!
> better lint for opam 1.2 files when using opam2

- appveyor-opam.sh
Fix for #250
The second commit is not intended for merge, it's just there to make the CI happy ...
> Update to opam 2.0 on AppVeyor

- .travis-docker.sh
> ensure `opam switch create` is not ambiguous

- .travis-docker.sh
The docker containers only support OPAM 1.2.2 or the latest release of opam 2 (so 2.0.1). `OPAM_VERSION` should only be permitted to select between `1` and `2`, therefore.
This updates the default to be `2` and adds a warning if `OPAM_VERSION` is set to `2.0.0`, etc.
> Correct Docker script support for OPAM_VERSION

- .travis-docker.sh
A tweak I failed to commit in #270...
> Minor fixup to Docker script

- travis-opam.opam
> pull opam for travis-opam from opam-repository

- .travis-ocaml.sh
The ppa isn't needed for the Bionic Travis image
> Bubblewrap is packaged in Bionic

- .travis-ocaml.sh
- .travis.yml
- README-travis.md
Not to be merged before ocaml/opam-repository#14842
> Add OCaml 4.09 support

- README-travis.md
> Add instruction for new packages.

- .travis-ocaml.sh
Fixes https://github.com/ocaml/ocaml-ci-scripts/issues/322 and https://github.com/ocaml/ocaml-ci-scripts/issues/326
cc @hannesm @XVilka
>  Remove opam 1.2 support and update homebrew support

- .travis-ocaml.sh
- .travis.yml
Hello, here is a PR for FreeBSD support in .travis-ocaml.sh
I tried it successfully with https://github.com/geneweb/geneweb (OCAML_VERSION=4.05)
> FreeBSD support in .travis-ocaml.sh

- .travis-ocaml.sh
Fixes issues encountered here: https://travis-ci.org/github/ocaml/opam-repository/jobs/682282143
> Temporary fix for opam-depext < 1.1.3 on FreeBSD

- README-travis.md
Is there anything more to add in the documentation concerning FreeBSD ?
> Mention FreeBSD in the documentation

- .travis-docker.sh
- Dockerfile
Just a draft for now. Need to ask around if it might break some setup.
Background post: https://discuss.ocaml.org/t/removing-fat-compiler-images-on-hub-docker-com-r-ocaml-opam2/6658/2
> Switch travis-docker to ocurrent images

- .travis-ocaml.sh
Also updates 4.11 to the latest release and moves the next preview to 4.14.
> Add support for 4.12 and 4.13
