ocaml/ocaml-ci-scripts

.travis-opam.sh
This reverts commit 2314075925fb196fbd85e38de78d19a0d1e149a2.
See https://github.com/avsm/opam-installext/issues/4
=> Revert "Use opam-installext"

.travis-mirage.sh, README.md
deployment keys being tied to the org/repo mean that the Xen `DEPLOY=1` build causes a travis failure. the additional test below stops the attempt at deployment if the keys are not visible in the environment.
i've also updated the readme post refactoring.
=> stop xen build failing when repo is forked

.travis-mirage.sh, .travis-ocaml.sh, .travis-opam.sh
Also deprecates OCaml 3.12.1 for these particular scripts, unless @dbuenzli can add 3.12.1 support to cmdliner.
=> Support forked invocation, use opam-depext and install depexts on REV_DEPS

.travis-ocaml.sh
These two issues bit me during release of ipaddr 2.6.0:
1. There should not be a default compiler case.
2. Exactly what I ask for should be installed.
=> Silently using a modern compiler is failure for testing

.travis-opam.sh
Inspired by <https://travis-ci.org/mirage/ocaml-cohttp/jobs/58307674#L1819> and the subsequent failure on <https://travis-ci.org/mirage/ocaml-cohttp/jobs/58307674#L2216>. I don't know if this is actually the issue as I can't seem to reproduce the Travis failure.
=> Run tests before optional dependencies in case depopts are dirty after uninstall

.travis-ocaml.sh
this is primarily needed for mirage-entropy-xen which depends on mnemonics only available in more recent compilers + as
=> if UPDATE_GCC_BINUTILS is set, install gcc-4.8 and binutils 2.24

README.md, travis_opam.ml
Fixes #30.
This hasn't been tested so it would be best to get @johnelse approval (or at least the scenario where he wanted this feature).
=> If TESTS=true, run tests during DEPOPTS run, too.

.travis-docgen.sh, README.md
I realise that this would probably need a bit of work to conform to the style of "script" in this repo. I've highlighted those in the pull request in the changes to the README but they'd be at least:
Just wanted to see if this could in principle go in before I do any of that.
I've got it in use in a couple of repos (there are "badges" on the README linking to the self-hosted docs):
* https://github.com/xapi-project/backtrace
* https://github.com/simonjbeaumont/ocaml-pci
=> RFC: Add support for updating docs on Github pages

travis_opam.ml
If directory caching is enabled for `.opam`, the previous process for adding pins will fail due to duplicate names, e.g., extra0, extra1, etc. Removing all pins except the default before attempting to add them
avoids this problem.
For those that are not using directory caching or are not using `EXTRA_REMOTES`, the behavior should be unchanged.
=> cache: remove extra pins before adding them back

.travis-ocaml.sh
Travis currently uses Ubuntu precise (12.04LTS).  When ```.travis-ocaml.sh``` adds "trusty" repo it breaks subsequent package installation with OPAM depexts.  Here is an example error message:
```
Not running as root, the following command will be run through "sudo":
apt-get install -qq -yy libhdf5-serial-dev
E: Unable to correct problems, you have held broken packages.
opam-depext: internal error, uncaught exception:
Failure("OS package installation failed")
```
This fix simply removes the extra package repos after they're needed.
See https://github.com/ocaml/opam-repository/pull/4831 for details.
=> Adding "precise" repo breaks OPAM depexts

travis_opam.ml
will address mirage/ocaml-uri#87 and other multi-distro failures
=> travis-opam: update OS package sets before a depext

.travis.yml, travis_opam.ml
Some repo can contain multiple opam files (e.g. mirage/mirage contains
mirage and mirage-types), so we need to look for `<pkg>.opam`
Fix https://github.com/mirage/mirage/issues/496
=> Better detection of opam files

appveyor-opam.sh
RE: https://github.com/fdopen/opam-repository-mingw/issues/12#issuecomment-191918017
- it should now work for all windows versions (32-bit and 64-bit)
- the environment is properly updated after `opam init`
- if possible, native symlinks are used for better compatibility with unix scripts (see e.g. https://github.com/mirage/ocaml-cstruct/issues/83 )
- you can now optionally pass a switch to the script (eg. `4.01.0+mingw32c` or `4.03.0+beta1+mingw64`) to select the compiler that should be installed.
=> appveyor: initialize the environment properly

.travis-docker.sh, .travis-mirage.sh, .travis-opam.sh, travis_opam.ml
Removal of `base-*` packages (as determined by having a version `base`) should not be attempted.
This patchset filters out packages that have a version of `base` from the packages to be removed. This fixes #93.
Also, `FORK_USER` and `FORK_BRANCH` field support was added to the `.travis-docker.sh` file to make it easier to experiment with modifications to this tool.
Also, mentions of `ocaml-travisci-skeleton` were updated to `ocaml-ci-scripts`.
=> Removal demands should be baseless

CHANGES
@avsm @samoht it would be nice to get #96 into the Docker images by releasing 1.0.3 in opam-repository and doing whatever is necessary to refresh the container images.
=> Prepare for 1.0.3

travis_mirage.ml
mirage 2.7.0 will generate an .xl.in file as part of the configure
phase. This file contains the virtual hardware configuration needed
by the kernel, with holes where the network bridges, disk images
and memory settings should go.
This patch ensures that any generated .xl.in file is checked into
the binary repo alongside the kernel that it describes.
Deployment scripts should use the .xl.in files as a template, so there
is no unexpected breakage if (for example) the virtual disk device
changes from xvda to xvdb, or if the VM is booted HVM rather than PV.
This is part of [mirage/mirage#443]
Signed-off-by: David Scott <dave.scott@docker.com>
=> mirage: check in any generated .xl.in file

.travis-ocaml.sh
..which can be seen e.g. in https://travis-ci.org/mirage/mirage-entropy/jobs/128767313
```
+echo installing a recent gcc and binutils (mainly to get mirage-entropy-xen working!)
installing a recent gcc and binutils (mainly to get mirage-entropy-xen working!)
+sudo add-apt-repository deb mirror://mirrors.ubuntu.com/mirrors.txt trusty main restricted universe
+sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
...
+sudo apt-get -qq update
+sudo apt-get install -y gcc-4.8
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
binutils cpp-4.8 gcc-4.8-base gcc-5-base libasan0 libatomic1 libcloog-isl4
libgcc-4.8-dev libgcc1 libgomp1 libisl10 libitm1 libmpc3 libmpfr4
libquadmath0 libtsan0
...
Get:6 …
```
=> trusty now comes with binutils 2.24

.travis-ocaml.sh
Before, we installed from SVN trunk instead.
(and trunk currently fails with:
```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/ocamlbuild
Target /usr/local/bin/ocamlbuild
is a symlink belonging to ocaml. You can unlink it:
brew unlink ocaml
```
)
=> On OS X, install 4.03 if the user asks for 4.03

.travis-ocaml.sh
Remove trailing spaces from `.travis-ocaml.sh` introduced by 05fd56af6bd2ee13ef53a642cb3e65e174982cb6.
=> Remove trailing spaces from .travis-ocaml.sh

appveyor.yml
Use the curl version that is already provided in the appveyor image, as it seems to work fine. When installing it manually the command becomes unavailable, resulting in error 127 (see e.g. https://ci.appveyor.com/project/samoht/ocaml-ci-scripts/build/1.0.41)
=> Use curl provided by appveyor

travis_mirage.ml
Recently noticed that forcing Travis to redo a deployment build when (e.g.,) upstream libraries have been updated or a `PIN` is introduced didn't seem to trigger a redployment: the invocation of `bzip2` failed because the target file already existed in the deployment repo.
This PR allows that case to succeed by first removing the target of the `bzip2` invocation.
=> Remove bzip2 target before invoking bzip2

appveyor-opam.sh
@fdopen do you use what you've added to line 20/23?
```
if [ $# -gt 0 ] && [ -n "$1" ]; then
SWITCH=$1
fi
```
I think it is best to use `OPAM_SWITCH` here to be consistent with TravisCI scripts. If you don't use it, do you mind if I remove these lines?
=> Allow to set OPAM_SWITCH on appveyor

.merlin, ci_opam.ml
This tries to reduce the amount of tests run when doing 'opam install -t -v PACKAGE', but there is some discrepancy between the packages reported by `OPAMBUILDTEST=true opam list --required-by PACKAGE` and `opam install -v -t PACKAGE`.
As a concrete example this happens for `conduit` with the updated CI script:
```
opam install  async_ssl lwt mirage-dns ssl tls "base-bytes" "base-ocamlbuild" "base-unix" "base64" "camlp4" "cmdliner" "conf-m4" "conf-ncurses" "conf-pkg-conf
ig" "conf-which" "cppo" "cstruct" "ipaddr" "js-build-tools" "js_of_ocaml" "logs" "lwt" "menhir" "mtime" "ocamlbuild" "ocamlfind" "ocplib-endian" "optcomp" "ou
nit" "ppx_core" "ppx_deriving" "ppx_driver" "ppx_optcomp" "ppx_sexp_conv" "ppx_tools" "ppx_type_conv" "qcheck" "qtest" "re" "result" "sexplib" "stringext" "to
pkg" …
```
=> Run depopts tests

appveyor.yml
Seems that there is a new conflict between different version of m4 installed by
cygwin.
=> Fix for appveyor after m4 update

.travis-docker.sh, .travis-ocaml.sh, .travis-opam.sh, appveyor.yml, ci_opam.ml, opam
Sorry for the delay. Here is take two on https://github.com/ocaml/ocaml-ci-scripts/pull/145 , using `jq` this time.
The Travis log folds may not belong in this PR, but might make it easier to read the Travis output, which is a lot longer now, and can be confusing on where each phase begins, hopefully the folds will help with that, let me know if I should make a separate PR for that.
=> Run depopts tests jq

appveyor.yml, ci_opam.ml
jq from cygwin didn't run (exited with code 127), use binary from github instead.
Accept solution.json from opam 1.3.0 too (ignore extra fields).
Here is a [failed Appveyor build](https://ci.appveyor.com/project/edwintorok/ocaml-ci-scripts/build/1.0.1), and here is a [successful Appveyor build](https://ci.appveyor.com/project/edwintorok/ocaml-ci-scripts/build/1.0.20) after this patch, and a [successful Travis build](https://travis-ci.org/edwintorok/datakit/jobs/196032769).
When I tested my previous PR I only tested on Travis, Appveyor was using `ci_opam.ml` from master instead of my PR branch, the above test is with a fork of ocaml-ci-scripts explicitly pointed to my branch `test-appveyor`, and this PR is the fix `fix-appveyor` but without the commit that changes `FORK_USER/FORK_BRANCH` …
=> attempt to fix appveyor build

.travis-ocaml.sh
Fix for #142
I've just run into it, too. It's confusing, if you request 4.03, but everything will be built with 4.04.
=> Update version on brew (system is now 4.04)

README-appveyor.md, appveyor-install.ps1, appveyor-opam.sh, appveyor.yml
I've improved th appveyor setup:
- The basic install step is now managed by the this repo instead of the individual `appveyor.yml` files. Cygwin is a rolling release, so workarounds are frequently necessary (like in the case of `jq` or `unzip`). A script is now downloaded and executed during the install step. If something must be changed, it can be updated centrally. The script is more verbose and should be able to deal with most changes itself.
- cygwin64 is used instead of cygwin32. cygwin64 is more reliable (less fork failures); it shouldn't make a difference performance-wise.
- OPAMJOBS is set to the number of processors provided by appveyor.
- the msvc toolchain is now supported by `appveyor-opam.sh`.
- README-appveyor.md was updated to reflect these changes.
The changes are backward …
=> new appveyor setup

README-travis-runner.md, travis-runner/Dockerfile, travis-runner/run.sh, travis-runner/travis-runner.sh
These changes add the means to be able to execute builds locally using https://github.com/ocaml/ocaml-ci-scripts/blob/master/.travis-docker.sh which is currently being used for Travis builds. 
The README has the details, but basically it sets up a "docker in docker" server and a client, in which the container required by the build is created and the build is executed.
Thanks!
=> containerized travis runner

.travis-ocaml.sh
See:
https://github.com/Homebrew/homebrew-core/commit/99ebe8f9ff89e3612bd22b44bf3a51b2bbff1227#diff-a4c89737c5b2155bec89dea5a85ec910
At the moment 4.05 will be used, if you specify 4.04 ...
=> brew has been updated to 4.05

.travis-docker.sh
Similar to BASE_REMOTE in .travis-ocaml.sh
This is useful when wanting to test alternative opam repositories that have
packages that haven't made it yet to main opam repository.
EXTRA_REMOTES could be used for that purpose, but that uses the repo in addition to main one,
with BASE_REMOTE you can test a particular opam remote in isolation.
=> Support BASE_REMOTE in .travis-docker.sh

.travis-ocaml.sh
With the current state, 4.05.0 uses homebrew "system" switch, which
results in 4.06.0 being actually used for testing. This resulted in
a bytes/string-related build failure under "OSX 4.05.0" for why3-base:
https://travis-ci.org/ocaml/opam-repository/jobs/300508089
> Setting environment variables from .travis.yml
> $ export OCAML_VERSION=4.05
> $ export OPAM_VERSION=1.2.2
> [...]
> OCaml version
> The OCaml toplevel, version 4.06.0
=> homebrew switched to 4.06.0 by default, update travis scripts

src/travis_mirage.ml
The previous `cd` doesn't actually descend into the given directory.  Use one that does.
[before](https://travis-ci.org/mirage/mirage-www/jobs/310990415) [after](https://travis-ci.org/mirage/mirage-www/jobs/310990414)
=> flags; cd fix

src/travis_mirage.ml
An attempt at an alternate fix for @mor1 's `mir-` prefix removal in #156 , which doesn't require coordination from the deploy side.
=> prefix Xen image; remove MIRDIR

README-travis.md, src/travis_mirage.ml
Fixes #197 .  The `mirage-www` deployment logic is now merged at https://github.com/mirage/mirage-www/blob/master/.travis-mirage-deploy.sh and called by the Travis setup in that repository.
=> remove deployment logic for mirage-www

.travis-docker.sh
Fix for #205 .  [before](https://travis-ci.org/yomimono/ocaml-cstruct/builds/332473642), [after](https://travis-ci.org/yomimono/ocaml-cstruct/builds/332573338) (`debian-unstable` failed to download a dependency of `jq` upstream in the "after" link, but the other distros are able to set up and run tests successfully.)
=> fix travis-docker: always remove travis-opam and install anew with depext

.travis-docker.sh
#205 [isn't fixed](https://travis-ci.org/yomimono/ocaml-cstruct/jobs/332473643#L4584) because we don't have an updated package definition for `travis-opam` at the time we run `depext -i`.  (It appears to work when testing with `FORK_USER` and `FORK_BRANCH` because in that case, we pin before updating, and therefore get a new package definition.)
Try, try again.
=> update opam before pulling a new travis-opam

.travis-ocaml.sh, README-travis.md
This PR achieves the dual purpose of addressing my request in #175 which will allow, for example, the first beta of OCaml 4.07.0 to be tested in a Travis matrix and also builds on this tweak to provide a new option `INSTALL_LOCAL` for the Linux hosts which instead of switching to a particular OCaml version will instead compile it locally, install it to `/usr/local` and then have opam use that compiler as a `system` switch.
The primary motivation of this is opam-repository continuous testing of system installation on a platform with "normal" security (i.e. not macOS).
The support can probably be extended to osx hosts, but it's not necessary for what I'm after as brew tracks latest OCaml already and the inability to virtualise macOS makes it more of a pain to test than even I am willing to …
=> INSTALL_LOCAL option: allowing a specific compiler to be tested as a "system" compiler

.travis-ocaml.sh, README-travis.md
Implements the apparent community consensus in https://github.com/ocaml/ocaml-ci-scripts/issues/110 .  You can see what this looks like for a user who was still trying to use `OCAML_VERSION=latest` at https://travis-ci.org/yomimono/mirage-tcpip/jobs/331934124#L486 .
=> remove "latest"; echo more help when OCAML_VERSION not set

.travis-docker.sh, .travis-mirage.sh, .travis-ocaml.sh, .travis-opam.sh, appveyor-install.ps1, appveyor-opam.sh, src/ci_opam.ml, src/jbuild, travis-opam.opam
Fixes #208 
Sorry ```jsonm``` depends on ```uutf``` (which itself depends on uchar) so it seemed to me that copying 
the files here was too much.
The solution is then to depend on ```jsonm``` and to remove any installed dependencies after.
This solution also fixes the fact that ```jbuilder``` was installed but not remove so the script wouldn't have detected if there was a dependency missing.
=> Replace the dependency over jq by jsonm

.travis-docker.sh
I've uploaded some Docker images for OCaml build environments with opam that include the +afl compiler variants (as well as afl tooling).  I'd like to use these as base images for workflows with `.travis-docker.sh`, which is possible if I can specify the hub user who should be hosting the base image.
=> allow the user to specify the Docker hub user from which to get the base image

src/ci_opam.ml
This should fix problems seen with appveyor. Sorry again.
=> Fix opam 1.3/2.0 json format parsing

.travis-docker.sh
When I specified a BASE_REMOTE that is completely separate from the
opam-repository, the older git version in the CentOS 7 container printed
a "no common commits" warning and failed to get the contents of the
master branch of the BASE_REMOTE.
I've fixed this by changing the fetch command to fetch the whole remote,
not just the master branch, this works in CentOS 7 too. This is probably
still more efficient for BASE_REMOTEs that are forks of opam-repository
than just deleting the directory and cloning BASE_REMOTE.
Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>
=> Fix BASE_REMOTE in .travis-docker.sh in CentOS 7 containers

.travis-ocaml.sh
This commit should be reverted once the problem is fixed upstream.
See e.g:
https://travis-ci.org/ygrek/ocurl/jobs/364068569#L597
https://travis-ci.org/ocamllabs/ocaml-ctypes/jobs/364740180#L2799
https://travis-ci.org/ocsigen/lwt/jobs/364332682#L125
=> Temporary workaround for python failure on OS X

README-travis.md
=> update some version numbers in travis readme

.travis-ocaml.sh, .travis.yml, README-travis.md
Not sure how to test it, but maybe Travis can do it for me? Let's see!
=> Add branches for OCaml 4.07

.travis-docker.sh
Previously the git pull did not work, because the master branch was
checked out, and it failed to merge from the 2.0.0 branch. So make sure
we check out the 2.0.0 branch first before pulling.
Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>
=> Fix .travis-docker.sh when opam 2 is used

.travis-docker.sh
This adds a fallback when `opam switch OCAML_VERSION` fails, attempting to create the corresponding switch, addressing #241.
This isn't perfect though since the pre-installed switches' names differ from the compiler names. One might wonder why their CI builds takes ages and have trouble figuring out it's because their `.travis.yml` contains
` - OCAML_VERSION=4.07.0` instead of `- OCAML_VERSION=4.07`.
Not sure what should be done to avoid this!
=> Create a new switch if not pre-installed

.travis-docker.sh
So far, .travis-docker.sh uses branch "master" of any BASE_REMOTE that
is being supplied. This commit adds support to optionally use a
different branch which is supplied via BASE_REMOTE_BRANCH.
The motivation is to enable versioning of the Opam repository that is
being used. When such a repository is used to describe the universe of
packages for a product, it is natural to evolve it and the desire to
refer to a past status arises naturally.
Comparing this to .travis-ocaml.sh, it seem that it supports branches in the base remote already by using the syntax `git://github.com/ocaml/opam-repository#2.0.0`. It might be desirable to unify this.
Signed-off-by: Christian Lindig <christian.lindig@citrix.com>
=> RFC: Add support for BASE_REMOTE_BRANCH

src/ci_opam.ml
Reverts ocaml/ocaml-ci-scripts#243
=> Revert "better lint for opam 1.2 files when using opam2"

.travis-ocaml.sh
Fixes #253 
2cf2846 : changes variable `OCAML_VERSION` used only on `install_ppa` for opam<2.0 to `SYS_OCAML_VERSION`.
=> Install system ocaml  for opam2

.travis-ocaml.sh
This [fixes](https://travis-ci.org/Chris00/ocaml-odepack/jobs/447836933#L742)  [issue 259](https://github.com/ocaml/ocaml-ci-scripts/issues/259).
=> Ensure the Travis opam init selects the compiler unambiguously

.travis-docker.sh
The `1.2` does not exist locally in the container so `git checkout 1.2` fails. This PR fixes this by fetching the branch from origin first.
=> Fix travis-docker when using opam 1.2

.travis-docker.sh
Another piece in the puzzle for https://github.com/ocaml/opam/issues/3662 - #267 ensures that newly built compilers in the container will install correctly by putting `ocaml-config.1` in the switch base packages where it belongs. That only works if you specify a full compiler to install (e.g. 4.05.0) - if the switch in the container (e.g. 4.05) is used, then hoisting the `opam update` doesn't help.
This temporary patch installs `opam-ed` and uses it to edit the `switch-state` file after the update/upgrade to ensure that `ocaml-config.1` is definitely in the base packages.
https://github.com/ocaml/opam/pull/3666 fixes this permanently - once that's deployed, this commit should be reverted.
=> Workaround opam remove -a problems

.travis-docker.sh
Workaround for https://github.com/ocaml/opam-repository/issues/12936
The workaround should work by having the base packages all upgraded first and not having to upgrade them upon `opam remove -a` which seems to cause the issue.
cc @dra27 @samoht 
cc @c-cube @mseri would you like to test with this version of the `.travis-docker.sh` script? Should just need to replace the original script link by this one: https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/9c602f881f2b55649011e37002f9177cbf9af8b2/.travis-docker.sh
=> ocaml-config issue workaround

src/ci_opam.ml
Dependencies like Coq take a long time to install.
=> verbose install to keep CI alive

.travis-ocaml.sh, README-travis.md
as suggested in https://github.com/ocaml/opam/issues/3548#issuecomment-431651465
it is unclear to me how the version numbering should work here:
- should there be a OPAM=2 which sticks to the latest release of opam (within major version 2)? (and/or OPAM=2.0 to specify the 2.0.X release series?)
- is there any need to specify exact versions (i.e. opam2.0.0, opam2.0.1)?
- when to phase out opam1 (1.1.2, 1.2.0, 1.2.2) support?
=> use opam 2.0.1 by default

.travis-docker.sh
@rjbou pointed out that I'd missed `opam switch set-base`. Here is a simpler solution than #268.
=> Simpler fix for opam remove -a

.travis-ocaml.sh
Travis has now support for Ubuntu trusty (and now use it for opam-repository CI) and in this version, OCaml 4.01 is not the version of OCaml that is available but rather OCaml 4.02 is. So when trying to install OCaml 4.01 the script will rather install OCaml 4.02 instead.
This PR fixes that by not installing the system compiler for 4.01
=> Fix .travis-ocaml.sh on trusty when installing OCaml 4.01

.travis-ocaml.sh
This fixes a regression introduced in df00917752 concerning the `install_ppa` function in `.travis-ocaml.sh`:
`install_ppa` first calls `add_ppa` but not `apt-get update`. It then calls `full_apt_version` (for the arguments of `apt_install`), which fails to see the version from the PPA.
See https://travis-ci.org/thpani/coachman/builds/458377031 for a failing travis build.
=> Update APT before querying apt-cache

.travis-ocaml.sh
This logic might want to be extended further after opam 2.1 is released (since requesting 2.0.2 is much more serious than requesting 2.0.3 after 2.1.0 exists), but I tire of being accused of over-engineering recently...
=> Warn if OPAM_VERSION specifies old release

.travis-ocaml.sh
I am not sure why it needs to be installed with apt?
But now it causes some real problem, see https://github.com/ocaml/opam-repository/pull/13713#issuecomment-475270065
Making sure camlp4 is installed only through opam fixes it, see https://travis-ci.org/ahrefs/devkit/builds/510055472
=> Do not install system camlp4

.travis-ocaml.sh
Currently it silently fails on 404.
=> Fail curl and report errors

dune-project
Avoids such errors: https://travis-ci.org/Chris00/ocaml-crlibm/jobs/516533307#L751 making all CI build fail.
=> Add the project name to dune-project

.travis-docker.sh
Travis started to fail today with (https://travis-ci.org/xapi-project/xcp-idl/builds/547278042?utm_source=github_status&utm_medium=notification):
```
[ERROR] Could not update repository "default": "/usr/bin/patch -p1 -i /home/opam/.opam/log/processed-patch-7-58c514" exited with code 1
```
Running locally with `opam update --debug` shows that this is happening:
```
00:00.148  PARALLEL                        Collected task for job 0 (ret:0)
00:00.149  PARALLEL                        Next task in job 0: /usr/bin/git fetch -q file:///home/opam/opam-repository --update-shallow +HEAD:refs/remotes/opam-ref
00:01.199  PARALLEL                        Collected task for job 0 (ret:0)
00:01.202  PARALLEL                        Next task in job 0: /usr/bin/git add .
00:02.968  PARALLEL …
```
=> Fix opam BASE_REMOTE problems

.travis-ocaml.sh, .travis.yml, README-travis.md
Fixes #297.  It seems that OCaml 4.08 is not yet available in Homebrew, but I expect it will be there soon.
=> Add OCaml 4.08 support.

.travis-docker.sh
This reverts commit 5a9e2983ebc494aef6dc85e5e53fd10087525dd6 and is here as a reminder for when opam 2.0.2 arrives - it can be merged once the containers on ocaml/opam2 are upgraded to 2.0.2
=> No longer need opam switch set-base workaround with opam 2.0.2

.travis-docker.sh, src/ci_opam.ml
Writing `PACKAGE=` to `env.list` means that `PACKAGE` is the empty string, rather than unset. This causes [confusing error messages](https://travis-ci.org/avsm/ocaml-dockerfile/jobs/550130401#L693)
cc @avsm
=> Don't write unset variables to env.list in Docker script

Dockerfile, Makefile
Well, now it is deprecated, time to remove it. Not sure what to do with `pkg/pkg.ml` though...
=> Remove jbuilder remnants

.travis-ocaml.sh
Since OCaml 4.08.1 has been released a few weeks ago, ocaml-ci-scripts needs to be updated to provide the latest version available.
=> Update latest OCaml 4.08 version

.travis-docker.sh
This PR allows to test switches such as `ocaml-variants.4.10.0+trunk` in Travis CI
=> Travis-docker: Allow non-standard (e.g. ocaml-variants) switches to be created

.travis-docker.sh
It is currently very hard to simply test packages against beta/rc or other ocaml-variants (flambda, ...) with the travis-docker script. This PR fixes this issue by introducing a new environment variable `OCAML_BETA` which when equal to `enable` adds the ocaml-beta-repository to the repositories used by opam to create new switches.
This change was tested successfully in `mdx`: https://travis-ci.org/realworldocaml/mdx/builds/635266545 (PR: https://github.com/realworldocaml/mdx/pull/204)
=> Travis-docker: Add a config variable to enable ocaml-beta

.travis-ocaml.sh, .travis.yml
This is a second PR in the same vein than https://github.com/ocaml/ocaml-ci-scripts/pull/319 but for `.travis-ocaml.sh`
This feature would allow to test more rigorously packages with beta or release candidate versions of the compiler and would warn early if something breaks with such a version.
=> Travis-ocaml: Add a config variable to enable ocaml-beta and allow unlisted compilers to be installed

.travis-ocaml.sh
Fixes an issue reported by @hhugo in https://github.com/ocaml/ocaml-ci-scripts/commit/340e8856d661f2393836d68fadccf46f20516c02#r37309533
=> Fix travis-ocaml when an opam installation is already present

appveyor-install.ps1
Updating gcc is not longer necessary, because appveyor updated their images and a recent enough version of gcc is now installed by default. The current instructions don't work any longer, because the most recent version of mingw64-i686-gcc-core would also require a newer versions of mingw64-x86_64-binutils.
This hopefully fixes #325
The second commit is not intended for merge. I will remove it, once the CI is happy.
=> fix appveyor install instructions

.travis-ocaml.sh
This removes the dependency of the ansible/bubblewrap PPA which has removed bionic builds.
Currently all tests on bionic fail, because the PPA can't be installed. [Example](https://travis-ci.org/github/didier-wenzek/ocaml-kafka/jobs/665881958).
=> Bionic has bubblewrap in repo

.travis-ocaml.sh
ci-opam uses Dune, which will install ocaml-secondary-compiler on OCaml < 4.07. If the project itself uses Dune, it then installs ocaml-secondary-compiler again which is slow and Carbon-creating 🙂
This PR simply makes `ocaml-secondary-compiler` part of the switch base for OCaml < 4.07 (the case expresssion is copied from a previous usage to be consistent - good luck with 3.12, 4.00 and 4.01 support!)
Here's a matrix from before [showing 4.02-4.06 taking nearly twice the time of the others](https://travis-ci.org/github/dra27/opam-file-format/builds/687175920) and then here's another [with the change where the builds are rather closer](https://travis-ci.org/github/dra27/opam-file-format/builds/687337962).
=> Don't build ocaml-secondary-compiler twice for Dune-based projects

.travis-docker.sh, .travis-ocaml.sh, .travis-opam.sh, src/ci_opam.ml
[This Travis log](https://travis-ci.org/github/dra27/opam-file-format/jobs/686603903) reveals a couple of errors in the folding in Travis. Firstly, the `prepare.ci` part is [not displayed correctly](https://travis-ci.org/github/dra27/opam-file-format/jobs/686603903#L207) and can't be opened; secondly, the `Installing.DEPOPTS` part appears to display correctly, but [can't be expanded](https://travis-ci.org/github/dra27/opam-file-format/jobs/686603903#L725). Turns out there are two issues:
- When you start a fold, there must be at least one line of text before the next fold is started (known: see https://github.com/travis-ci/travis-ci/issues/1352#issuecomment-203523502). When `DEPOPTS` is set to a value, nothing is displayed between the two folds. My solution for this is simply to display a …
=> Three minor fixes

.travis-ocaml.sh, .travis.yml
Partially fixes #316 by adding ARM64 support (the 2 other new platforms are not available as ready-to-use opam binaries so it's a little more tricky. See https://github.com/ocaml/opam/releases/tag/2.0.7)
Also temporarily fixes issues in 4.12 trunk (https://github.com/ocaml/ocaml/pull/9798)
=> Add support for ARM64 + tmp fix for 4.12

.travis-ocaml.sh
The MacOS check in opam-repository fails way too often during `brew update` as it apparently takes more than 10 minutes and does not show any output due to the `&> /dev/null`.
Hopefully this change is fine and does not produce an unreasonable amount of log
=> Show brew update's output to avoid travis' 10mins timeout

.travis-docker.sh
I'm seeing the following error on travis-ci which I think should be fixed by removing `;;`?
```bash
+from=ocaml/opam:debian-stable
244+echo FROM ocaml/opam:debian-stable
245+echo WORKDIR /home/opam/opam-repository
246./.travis-docker.sh: line 58: syntax error near unexpected token `;;'
247The command "bash -ex ./.travis-docker.sh" exited with 2.
248
249
250Done. Your build exited with 1.
```
=> Fix syntax error on docker travis build?

.travis-docker.sh
The new `ocaml/opam` images lack tags `<distro>` which were aliases to `<distro>-<latest_version>` in the old `ocaml/opam2` images.
*Issue reported by @hannesm*
=> travis-docker: Fix use of latest distros

.travis-docker.sh
Reverts ocaml/ocaml-ci-scripts#350
This is now fixed upstream in the docker images themselves. cc @hannesm
=> Revert "travis-docker: Fix use of latest distros"

appveyor-install.ps1
There is some weirdness with file checks going on on appveyor and using HTTPS will prevent potential proxies with meddling with the data.
Attempts to solve problems in builds like these: https://ci.appveyor.com/project/ygrek/ocaml-extlib/builds/44404178
=> Use HTTPS mirror

.travis-ocaml.sh
Small typo in a `case` for selecting an ocaml version
=> Fix typo in ocaml version number
